# Saber por departamentos y municipios



```{r}
library(rpart)
library(rattle)
library(ggplot2)
library(grid)
library(plyr)
library(FactoMineR)
library(gridExtra)
library(maptools)
library(rgdal)
```

Para empezar, carguemos los promedios por colegio de las pruebas Saber 11 de 2013, disponibles [acá](http://www.icfes.gov.co/resultados/saber-11-resultados?id=39) para descarga. 

```{r}
saber2013.df <- read.csv("./data/saber2013.csv")
saber2013.df$evaluados <- as.numeric(gsub(",","", as.character(saber2013.df$evaluados)))
```

## Mapa promedios (matemática y lenguaje) colegios públicos 2013

```{r}
saber2013.df$aporte.matematica <- saber2013.df$matematica * saber2013.df$evaluados
saber2013.df$aporte.lenguaje <- saber2013.df$lenguaje * saber2013.df$evaluados

saber2013.publicos.df <- saber2013.df[saber2013.df$naturaleza == "OFICIAL",]

# Calculemos de paso el número de colegios públicos

dim(saber2013.publicos.df)
```

Armemos un nuevo dataframe por municipio que contenga: suma de los aportes de cada colegio y total de estudiantes evaluados.

```{r}
saber2013.municipios.df <- ddply(saber2013.publicos.df, ~cod_municipio, summarize, aportes.mat = sum(aporte.matematica), aportes.leng = sum(aporte.lenguaje), total.evaluados = sum(evaluados), municipio = municipio[1], departamento = departamento[1])
```

```{r}
saber2013.municipios.df$promedio.mat <- saber2013.municipios.df$aportes.mat / saber2013.municipios.df$total.evaluados
saber2013.municipios.df$promedio.leng <- saber2013.municipios.df$aportes.leng / saber2013.municipios.df$total.evaluados
```

```{r}
summary(saber2013.municipios.df)
```

Carguemos el mapa:

```{r}
municipios <- readOGR(dsn="./mpio/", layer="mpio")
municipios@data$id <- rownames(municipios@data)

#Armemos el código de municipio para que quede en el formato apropiado.

municipios@data$codigo_municipio <- as.numeric(gsub(" ", "", paste(municipios@data$DPTO, municipios@data$MPIO)))
```

```{r}
municipios.data <- merge(municipios@data, saber2013.municipios.df, by.x="codigo_municipio", by.y="cod_municipio", all.x=T, all.y=F)
```

```{r}
deptos <- readOGR(dsn="./depto/", layer="depto")
levels(deptos@data$DPTO) <- as.numeric(levels(deptos@data$DPTO))
deptos@data$id <- rownames(deptos@data)
deptos.df <- fortify(deptos)
```

```{r}
municipios.df <- fortify(municipios)
municipios.df <- join(municipios.df, municipios.data, by="id")
```

```{r}

th <- theme(axis.text.x = element_blank(), 
            axis.text.y = element_blank(), 
            axis.ticks= element_blank(),
            axis.title=element_blank(),
            panel.grid.major=element_blank(), 
            panel.grid.minor=element_blank(), 
            plot.background=element_blank(), 
             panel.background=element_blank()
#             panel.border=element_blank()
            )

p <- ggplot(data=municipios.df, aes(x=long, y=lat, group=group)) + coord_equal() + th
p <- p + geom_path(color="white")
p.mat <- p + geom_polygon(aes(fill=promedio.mat))
p.mat <- p.mat + scale_fill_gradient(name="Promedio en Matemática\nColegio Públicos\n(Saber 11 - 2013)",
                               low="#ffffcc", high="#ff4444", 
                               space="Lab", na.value="grey40",
                               guide="colourbar")
p.mat <- p.mat + geom_path(color="white", data=deptos.df, size= 0.2,  aes(x=long, y=lat, group=group))

p.mat
```

```{r}
p.leng <- p + geom_polygon(aes(fill=promedio.leng))
p.leng <- p.leng + scale_fill_gradient(name="Promedio en Lenguaje\nColegio Públicos\n(Saber 11 - 2013)",
                               low="#ffffcc", high="#ff4444", 
                               space="Lab", na.value="grey40",
                               guide="colourbar")
p.leng <- p.leng + geom_path(color="white", data=deptos.df, size= 0.2,  aes(x=long, y=lat, group=group))

p.leng
```

```{r}
mat.leng.municipios <- arrangeGrob(p.mat,p.leng, nrow=1)
ggsave("./figure/mat.leng.municipios.png", mat.leng.municipios, width=30, height=15)
```

```{r}
barplot_mat <- ggplot(saber2013.municipios.df, aes(x=promedio.mat)) + 
    geom_histogram(aes(y=..density..),      # Histogram with density instead of count on y-axis
                   binwidth=.5,
                   colour="black", fill="white") +
    geom_density(alpha=.4, fill=colors()[91]) +  
  xlab("Promedio en Matemática") +
  ylab("Proporción de colegios") + 
  ggtitle("Distribución de Promedios de Matemática por Municipio\n(Colegios Públicos - Saber 11 - 2013)")

barplot_mat
```

```{r}
barplot_leng <- ggplot(saber2013.municipios.df, aes(x=promedio.leng)) + 
    geom_histogram(aes(y=..density..),      # Histogram with density instead of count on y-axis
                   binwidth=.5,
                   colour="black", fill="white") +
    geom_density(alpha=.4, fill=colors()[91]) +  
  xlab("Promedio en Lenguaje") +
  ylab("Proporción de colegios") + 
  ggtitle("Distribución de Promedios de Lenguaje por Municipio\n(Colegios Públicos - Saber 11 - 2013)")

barplot_leng
```

```{r}
barplot_evaluados <- ggplot(saber2013.municipios.df, aes(x=total.evaluados)) + 
      geom_density(alpha=.7, fill=colors()[91]) + 
      scale_x_log10() +
  xlab("Número de evaluados") +
  ylab("Proporción de colegios") + 
  ggtitle("Distribución de número de evaluados por municipio\n(Colegios Públicos - Saber 11 - 2013)")

barplot_evaluados
```

```{r}
ggsave("./figure/dist.evaluados.municipios.png", barplot_evaluados, width=10, height=10)
```

```{r}
median(saber2013.municipios.df$total.evaluados)
```

```{r}
distribuciones.mat.leng <- arrangeGrob(barplot_mat,barplot_leng, nrow=2)
ggsave("./figure/dist.mat.leng.municipios.png", distribuciones.mat.leng, width=15, height=30)
```

```{r}
mat.leng <- arrangeGrob(p.mat, barplot_mat, p.leng, barplot_leng, nrow=2)
ggsave("./figure/distribuciones-promedios.png", mat.leng, width=20, height=20)
```

p.mat,p.leng

```{r}
ranking.mat <- saber2013.municipios.df[with(saber2013.municipios.df, order(-promedio.mat, municipio)), ]
ranking.leng <- saber2013.municipios.df[with(saber2013.municipios.df, order(-promedio.leng, municipio)),]
```

```{r}
top50.mat <- ranking.mat[1:50,]
write(paste(1:50, top50.mat$municipio, "(", top50.mat$departamento, ") Puntaje:", round(top50.mat$promedio.mat,2)), file="output_files/top50.mat.txt", sep="\n")
```


```{r}
top50.leng <- ranking.leng[1:50,]
write(paste(1:50, top50.leng$municipio, "(", top50.leng$departamento, ") Puntaje:", round(top50.leng$promedio.leng,2)), file="output_files/top50.leng.txt", sep="\n")
```

```{r}
cremedelacreme <- intersect(top50.mat$cod_municipio, top50.leng$cod_municipio)
top.publicos <- saber2013.municipios.df[saber2013.municipios.df$cod_municipio %in% cremedelacreme,]
top.publicos <- top.publicos[with(top.publicos, order(-promedio.mat, -promedio.leng)),]
write(paste(1:nrow(top.publicos), ") ", top.publicos$municipio, " (", top.publicos$departamento, ") \n   Puntaje Matemática: ", round(top.publicos$promedio.mat,2), "\n   Puntaje Lenguaje: ", round(top.publicos$promedio.leng,2), sep=""), file="output_files/top.publicos.txt", sep="\n")
```

```{r}
top110.mat <- ranking.mat[1:110,]
write(paste(1:110, ") ", top110.mat$municipio, " (", top110.mat$departamento, ") Puntaje: ", round(top110.mat$promedio.leng,2), " Número de estudiantes: ", top110.mat$total.evaluados, sep=""), file="", sep="\n")
```


```{r}
top110.leng <- ranking.leng[1:110,]
write(paste(1:110, ") ", top110.leng$municipio, " (", top110.leng$departamento, ") Puntaje: ", round(top110.leng$promedio.leng,2), " Número de estudiantes: ", top110.leng$total.evaluados, sep=""), file="", sep="\n")
```

```{r}
toponepercent <- intersect(top110.mat$cod_municipio, top110.leng$cod_municipio)
mejores.publicos <- saber2013.municipios.df[saber2013.municipios.df$cod_municipio %in% toponepercent,]
mejores.publicos <- mejores.publicos[with(mejores.publicos, order(-promedio.mat, -promedio.leng)),]
write(paste(1:nrow(mejores.publicos), ") ", mejores.publicos$municipio, " (", mejores.publicos$departamento, ") \n   Puntaje Matemática: ", round(mejores.publicos$promedio.mat,2), "\n   Puntaje Lenguaje: ", round(mejores.publicos$promedio.leng,2), " Número de estudiantes: ", mejores.publicos$total.evaluados, sep=""), file="output_files/mejores.publicos.txt", sep="\n")
```

```{r}
ranking <- ranking.leng[,c('municipio', 'departamento', 'promedio.mat', 'promedio.leng', 'total.evaluados')]
names(ranking) <- c('Municipio', 'Departamento', 'Matemática', 'Lenguaje', 'Evaluados')
ranking$Matemática <- round(ranking$Matemática, 2)
ranking$Lenguaje <- round(ranking$Lenguaje, 2)
write.csv(ranking, file="~/Documents/GitHubPages/informe/app/rank.csv", row.names=FALSE)
```